### ISSUE TITLE
[Feature Request] Pre-install AWS CLI on all workspace types

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#11]
I'm not sure if we already have them installed, but would be nice to have the AWS CLI installed on workspaces as well.

**Comment by fergusonsha-umkc** [comment]
This will be completed as part of the rclone mount integration into the workspace templates, as its a requirement for the startup script.

**Comment by fergusonsha-umkc** [comment]
@aaronmbruce or, if you want, can you bake it into the software preinstall script you've been maintaining?

**Comment by aaronmbruce** [comment]
This has been added
