### ISSUE TITLE
[Bug] Can not install python packages 

### ISSUE THREAD

**Issue by ShraaboniSarker** [Missouri-BMI/service-workbench-on-aws#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Versions (please complete the following information):**
 - Release Version installed [e.g. v1.0.3]

**Additional context**

**Comment by ShraaboniSarker** [comment]
@fergusonsha-umkc @aaronmbruce  I have just installed anaconda in AWS windows work space. but can not find "Anaconda Prompt" in the work space.
Can not install python packages. need to solve this issue asap.

**Comment by fergusonsha-umkc** [comment]
@vasanthi can you please have your team look into this with Shraaboni, and if unable to determine the resolution, please escalate to Aaron and I.  Thanks! :)

**Comment by vasanthi014** [comment]
> @fergusonsha-umkc @aaronmbruce I have just installed anaconda in AWS windows work space. but can not find "Anaconda Prompt" in the work space. Can not install python packages. need to solve this issue asap.

@ShraaboniSarker These kind of questions should come to me. You need assistance with installing anaconda in your windows service workspace, this is not a bug in the service workbench. 

@soliman455 Will you be able to have a screen share session with @ShraaboniSarker today or tomorrow to help her with the installation?

**Comment by ShraaboniSarker** [comment]
@vasanthi014 I have already installed anaconda in the Windows service workbench. I don't need support for installation. I am  facing difficulties with installing python packages.
Dr. Song told me to create issue under this repo.
![Screenshot 2021-11-17 at 3 31 33 PM](https://user-images.githubusercontent.com/27828078/142285750-5df8fcae-2bfd-4d07-94a0-12edef97670b.png)

**Comment by vasanthi014** [comment]
Do you see any error when you install packages? Can you share screenshots?

**Comment by ShraaboniSarker** [comment]
no the installation process was successful. but when trying to access conda environment it is not appearing in the command line. Also can not access " conda prompt " from Work space.
