### ISSUE TITLE
[Misc] Redundant Study Clean-up

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#13]
I have created the following redundant Org Studies and would like to clean them out: 
1. GPC-MUIRB2057285-GROUSE-ALS
2. Test-S3-Sync-Under-OrgStudy-Song

**Comment by fergusonsha-umkc** [comment]
Will tackle this today :)

**Comment by fergusonsha-umkc** [comment]
Studies removed.
