### ISSUE TITLE
[Bug] Sagemaker workspace cannot be terminated normally under Research-GPC account

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#16]

**Comment by fergusonsha-umkc** [comment]
Re-testing this against Research-GPC and Application-Prod to determine if its account-specific, possibly fixed by Friday's bug hunt, etc.

**Comment by fergusonsha-umkc** [comment]
Both tests terminated successfully!  Closing this out, but **if it happens again let's make sure to note in detail all the circumstances under this issue, and re-open it.**

![image](https://user-images.githubusercontent.com/81329060/146824685-7c64afa1-eb1b-4df3-8a32-108830f0ff81.png)
