### ISSUE TITLE
Patch Management in AWS Environment

### ISSUE THREAD

**Issue by vyshu1094** [Missouri-BMI/service-workbench-on-aws#27]

**Comment by vyshu1094** [comment]
From: Anye, Ernest <[anyeet@health.missouri.edu](mailto:anyeet@health.missouri.edu)> 
Sent: Wednesday, May 18, 2022 8:48 AM
To: Ferguson, Shaun <[fergusonsha@umkc.edu](mailto:fergusonsha@umkc.edu)>; Bruce, Aaron <[abruce@umkc.edu](mailto:abruce@umkc.edu)>; Baerwald, Charles H. <[baerwaldc@missouri.edu](mailto:baerwaldc@missouri.edu)>; Paka, Vyshnavi <[vpknx@health.missouri.edu](mailto:vpknx@health.missouri.edu)>
Cc: Mandhadi, Vasanthi (Medical Research Office) <[mandhadiv@health.missouri.edu](mailto:mandhadiv@health.missouri.edu)>; Song, Xing <[xsm7f@health.missouri.edu](mailto:xsm7f@health.missouri.edu)>
Subject: Patch Management in AWS Environment
 
Good morning,
 
Following our meeting yesterday, I am starting this conversation so that we can work on getting together to discuss patch management in our AWS environment. Based on what we discussed yesterday:
1. Shaun/Aaron will do some testing in Dev to apply patches to some EC2 instances
2. Once that is complete, the group will meet with Charlie to look into options to schedule a Qualys “scan” on the patched EC2 instances. My understanding is that Qualys agents report to the appliance every 4 hours
 
Shaun, please let the group know whenever your team has completed the patching so Vyshnavi can set up the meeting.
 
Thank you,
 
Ernest Anye, DrIT, CISSP

**Comment by fergusonsha-umkc** [comment]
Closing, merged with Missouri-BMI/NextGen_Cloud_Architecture_AWS#107

**Comment by fergusonsha-umkc** [comment]
Merged with Missouri-BMI/NextGen_Cloud_Architecture_AWS#107
