### ISSUE TITLE
[Feature Request] Rclone-Mount automation enhancement for external-account-workspace to external-study use case

### ISSUE THREAD

**Issue by fergusonsha-umkc** [Missouri-BMI/service-workbench-on-aws#28]
The original registration of the external data source for the GROUSE-CDM-Staging study was done correctly, from the perspective of how this version of Service Workbench intends things. I failed to realize we've never had an rclone-mounted external data source study on a workspace running under the external Research-GPC account, fully automatically deployed at least. The SAS workspaces are still Outback-Engineering-centric in design, so there's still some more customization to develop around the aforementioned use case where an external research account is in play. The one situation we have which is closest to this, are the ALS-NLP workspaces and study, and those were deployed and manually customized (as noted in their description) prior to the rclone-mount automation template development, so I'm now inspecting what the roles and policies those use all provide for, to determine how I got it to work back then.

**Comment by fergusonsha-umkc** [comment]
Looks like this has to do with the Trust Relationship policy defined on the 'swb-*-app-*' and 'swb-*-fs-*' roles... potentially, so that the resource account the workspaces get launched under are permitted to use the role and policy, not just the main SWB account...

**Comment by fergusonsha-umkc** [comment]
This won't get attention until after we get past Service Workbench upgrades and rollout of the TRE environment.  In the meantime, awscli and the AWS S3 web console can be used to interact with cross-account buckets from within workspaces, and extra EBS volumes provisioned and size:cost balanced according to use case needs.  This is what would be required of non-rclone-mounted study buckets too, and what we did to resolve the catalyst problem report for this enhancement request.

**Comment by vasanthi014** [comment]
@fergusonsha-umkc Will get back to this after the SWB upgrade

**Comment by fergusonsha-umkc** [comment]
This is working under SWB v5.2.7
