### ISSUE TITLE
Mystery Charge Observed

### ISSUE THREAD

**Issue by spinkac** [Missouri-BMI/service-workbench-on-aws#29]
One of my workspaces, Spinka-workspace-SWB-demo, is showing a cost of $5.52 for yesterday. When I dig into the details, it appears to be having a charge of $5.76 everyday for the past two weeks or so. However, I have not used this workspace at any point recently. Also, I have used other workspaces, and this one has not shown up as available while I have been using the other workspace. Costs on the other workspace (SAS-Workspace-Tumor-Table-EDC) are as expected.

Hoping this is not a sign of a problem, and sorry that I didn't notice this sooner!

**Comment by vasanthi014** [comment]
@aaronmbruce Can you please take a look at this workspace and see what happened. Also, stop it since no one is using it.

**Comment by aaronmbruce** [comment]
This was likely my fault. I was updating some instances and I must have left this one running

**Comment by spinkac** [comment]
@aaronmbruce @sxinger So that workspace still appears to be creating costs at the rate of $5.76 per day, while continuing to appear in my stopped list. I don't know why this is happening, and I still have not started that workspace.

**Comment by aaronmbruce** [comment]
Looks like it was out of sync with SWB. I have manually stopped it now.

**Comment by sxinger** [comment]
> Looks like it was out of sync with SWB. I have manually stopped it now.

Are we expecting such drift to happen again?

**Comment by fergusonsha-umkc** [comment]
I've not dug in deep on this yet, but quick question/reminder:  storage costs will accrue daily regardless of stopped or started state, on workspaces, they only go away when a workspace is terminated (which is why its best to terminate and relaunch whenever possible, if putting it on hiatus for a while).  This cost has already been considered and ruled out?

**Comment by spinkac** [comment]
@fergusonsha-umkc @sxinger  I cannot make any guarantees, however, all of my other workspaces show no costs when I am not using them. So up until today, my BESTMED workspace showed $0.00 for the cost, as I had not used it in a month.

**Comment by fergusonsha-umkc** [comment]
OK, and the storage cost is per GB per _month_ also I just reminded myself, which probably isn't enough of a trickle over that timespan to reflect much in the SWB cost per day meter unless you've got tens to hundreds of terabytes of block storage attached to the workspace... I'll do some investigating, but, to answer Dr. Song's question: we can't expect the unexpected, so no it should not be a recurring problem, but it's certainly something I'll keep an eye out for more often, and with the upgrade coming within the next month, especially if it happens again when we're on the latest and ostensibly more debugged release of SWB.

**Comment by fergusonsha-umkc** [comment]
I believe I know why the workspace status got out of sync, however.  The status is not the actual EC2 instance state being monitored, it's a DynamoDB field in the entry for the workspace, that gets updated as part of the Service Workbench workflows that are triggered and run by clicking the Start/Stop/Terminate button.  It updates that field to reflect the last known status of that workspace per the workflow completion, and the UI renders accordingly.

If the EC2 instance was started outside of Service Workbench, directly from the AWS EC2 web console or via awscli, then Service Workbench is wholly unaware of it and the status field remains in its last set value.  So we as admins need to be very cognizant of EC2 instance states and make sure if we started one for backend administrative maintenance, we stop it so it's consistent with the Service Workbench status.  We can somewhat rely on the auto-stop implementation, but we've seen it vary in sensitivity based on EC2 instance resources and any background processes that might keep the CPU idling just above the trigger threshold.  I think that was the case here, based on the Monitoring graphs on the EC2 instance from the time period where this was observed.

So, given those factors, we know what to expect under the presumption of increased diligence toward this behavior of the software :)

**Comment by sxinger** [comment]
Could think about include something like "SWB drift detection and resolution" to be part of the admin SOP in https://github.com/Missouri-BMI/NextGen_Cloud_Architecture_AWS/wiki

**Comment by fergusonsha-umkc** [comment]
Done: https://github.com/Missouri-BMI/NextGen_Cloud_Architecture_AWS/wiki/Workspace-Status-Drift-and-Resolution
