### ISSUE TITLE
[Investigation] unexpected workspace termination

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#33]
**Describe the bug**
Two students in my class (HMI7001 Fall2022) have experienced unexpected termination of their workspaces. They were accessing their workspace at least twice a week (in class), so it shouldn't have triggered the unuse alert. The following is one of the workspaces that got terminated this week: 

![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/19035729/202488116-26822e5b-f706-40f7-a019-747fa3441c1b.png)

Please help investigate.

**Comment by fergusonsha-umkc** [comment]
AFAIK we have not been terminating workspaces yet, only warning.  @aaronmbruce agreed?
I will look into it.

**Comment by fergusonsha-umkc** [comment]
Before we mark this as a Bug lets make sure no user interaction was in play.

**Comment by soliman455** [comment]
Just to confirm from my end, the auto termination feature is not yet implemented.

**Comment by sxinger** [comment]
I confirmed with both users, they were pretty sure that they didn't hit the termination button.

**Comment by fergusonsha-umkc** [comment]
We can verify that with CloudWatch logs.

**Comment by fergusonsha-umkc** [comment]
Can you provide some more details about which two students and which two workspaces, please?

**Comment by sxinger** [comment]
> Can you provide some more details about which two students and which two workspaces, please?

I have provided a screenshot in the description about the most recent incidence, which is for user "Terri Benskin" (also in the screenshot). Can we start the investigation from this one?

**Comment by fergusonsha-umkc** [comment]
I already have but I would like to have all the details, this is not too much to ask in return.

**Comment by sxinger** [comment]
> I already have but I would like to have all the details, this is not too much to ask in return.

That's all the details I have got from her so far. She noticed that this instance got terminated on 11/15 during our Tuesday class. May I know what additional details you would like to obtain?

**Comment by fergusonsha-umkc** [comment]
You said 2 users and 2 workspaces.  Only one user and workspace detail has been provided.  Whose is the other user and workspace?

**Comment by sxinger** [comment]
The other incidence is for user "Olabode Ogundele". But since it happened quite sometime ago, I'm not sure how much accurate details I can retrieve from him.

**Comment by fergusonsha-umkc** [comment]
OK, that helps.

**Comment by fergusonsha-umkc** [comment]
The DynamoDB entry for Terri Beskin's workspace indicates last updated by her user id on 10/27, and the deleted CloudFormation stack corroborates that timestamp as when it got terminated.  If it had been terminated outside of Service Workbench's workflow for doing so, the workspace status would be out of sync, and not have the terminated status in DynamoDB.  This indicates that the Terminate button was pressed, and that could only be done by her or by Aaron or myself.  I'll see if I can determine who exactly that could have been, in CloudWatch.

**Comment by fergusonsha-umkc** [comment]
The workspace for Olabode Ogundele presents the same, but with just an hour of time from created by that user id and then last updated by that user id, on Oct 20th, which also corresponds with the CloudFormation stack's deletion timestamp.

**Comment by fergusonsha-umkc** [comment]
Here is the CloudWatch log entry for Terri Beskin's workspace, the "actor" entry is a user id and it matches Terri's user id.  This means she pressed Terminate, accidentally or on purpose, and misremembered about it over 2 weeks later.
![image](https://user-images.githubusercontent.com/81329060/202503881-6c0aa876-c5fe-4c7e-ad2f-0d75e7e128e0.png)


I do not expect a different finding for Olabode Ogundele's workspace(s) but I can verify those each as well, if required.
