### ISSUE TITLE
Increase storage in Yaswitha's SAS SWB workspace

### ISSUE THREAD

**Issue by vasanthi014** [Missouri-BMI/service-workbench-on-aws#34]
Please make the following changes

Increase E: (Export) drive storage to 2TB
Increase T: drive(SAS Temp) storage to 1TB
Refer to https://github.com/Missouri-BMI/P_2_SASDB_EDC/issues/58 for background

**Comment by fergusonsha-umkc** [comment]
What is the workspace name/id please? :)

**Comment by vasanthi014** [comment]
@Yaswitha-MU What is the name/id of your SWB workspace where you run queries against CDM

**Comment by Yaswitha-MU** [comment]
PreventableBMI/870687ca-5295-44d0-b1a8-8eff7d0d8605

**Comment by fergusonsha-umkc** [comment]
Resized!

**Comment by Yaswitha-MU** [comment]
Thank you @fergusonsha-umkc
