### ISSUE TITLE
SWB access to Vyshnavi

### ISSUE THREAD

**Issue by vasanthi014** [Missouri-BMI/service-workbench-on-aws#35]
@vyshu1094 already has an AWS account, she want to launch a windows SWB workspace to use PowerBI desktop to create PCORnet study metrics dashboard.

Since there is no SWB study/organization for PMs she can be added to "NextGenBMI-Outback-Engineering"

**Comment by fergusonsha-umkc** [comment]
Got her added to the SWB researchers access group and added/activated her user entry in the UMBMIAWS SWB application.  She should be able to log in at https://aws.nextgenbmi.umsystem.edu now, but let me know of any issues.

**Comment by vyshu1094** [comment]
@vasanthi014 @fergusonsha-umkc I got the access. Thanks much!
