### ISSUE TITLE
Service Workbench Major Release Upgrade: Ready for Production!

### ISSUE THREAD

**Issue by fergusonsha-umkc** [Missouri-BMI/service-workbench-on-aws#36]
We've done buildout and testing under the SWB Sandbox account, and used that to do a concise procedural upgrade of the SWB Application-Dev account, and now we are ready to do SWB Application-Prod!  Good news, and even better news that all stopped workspaces survived the leap from v3.3 to v5.2 and were fully operational after the post-upgrade remapping to their corresponding new product-version entries :)

Per Dr. Song's planning notes, now we need to send out a proactive communication to production users notifying them at least 1 week in advance of the 8-hour maintenance window (evening or weekend) so that they can make any research data backups or study data syncs as they wish (less critical now that we have verified workspace stability across the upgrade, but still important).  I think probably the wording on how to do it, from the >30 days stopped workspace notification email template, could be re-used.  The only other thing they'd need to know is when the 8-hour maintenance window would start, and that Service Workbench will be offline for everyone until the work is complete.

I'd love to get this wrapped up prior to Christmas and Winter Break, but certainly will defer to your decision there.

**Comment by fergusonsha-umkc** [comment]
Just curious as to where the decision stands about when this maintenance window will be planned for? Thanks :)

**Comment by tmcmahonMU** [comment]
I was told @vasanthi014 would determine the maintenance window, but she it out until the 16th.

**Comment by fergusonsha-umkc** [comment]
If a decision can be collaborated on in her absence, aside from Dec 17th, 24th, and 25th I can perform the work any day this month.  I'd really love to get it in this same year :) Would doing it over Winter Break be amenable?

**Comment by tmcmahonMU** [comment]
@mosaa can you coordinate a date in @vasanthi014 absence?

@sxinger is your class finished for the semester or do they still need access to SWB prior to winter break?

**Comment by sxinger** [comment]
My class will conclude by the end of this final week. But the students will need their access to the workspace until 20th, the last day of turning in their final project. 21st, 22nd, or 23rd or a day during winter break sounds good to me.

**Comment by sxinger** [comment]
@soliman455 is this the final email we sent out for the 30-day termination notice? https://github.com/Missouri-BMI/service-workbench-on-aws/issues/21#issuecomment-1282914971

**Comment by soliman455** [comment]
> @soliman455 is this the final email we sent out for the 30-day termination notice? [#21 (comment)](https://github.com/Missouri-BMI/service-workbench-on-aws/issues/21#issuecomment-1282914971)

No. We used another ticket to create the finalized template. https://github.com/Missouri-BMI/service-workbench-on-aws/issues/31#issuecomment-1306176291  . This one is the final template.

**Comment by tmcmahonMU** [comment]
I suggest either Thur 12/22 in the evening with @Yaswitha-MU sending the notice when she returns on Mon morning or if that doesn't work then maybe Tue 12/27. 

Anyone have issues with the 22nd?

**Comment by fergusonsha-umkc** [comment]
I will be prepared for either choice.  I'm on a family trip to visit relatives between the 21st and the 3rd but that won't be a barrier for cloud work :)

**Comment by tmcmahonMU** [comment]
After discussion with Russ, the date is set for 12/27. Downtime will be 4-8 hours. If anyone has any issues with this date, update this ticket by COB tomorrow.

@Yaswitha-MU can you send out a message on Monday to let users know about the downtime?

**Comment by Yaswitha-MU** [comment]
@fergusonsha-umkc: Can I get the list of SWB users?

**Comment by fergusonsha-umkc** [comment]
> @fergusonsha-umkc: Can I get the list of SWB users?

@Yaswitha-MU Yes I will compile that and send it via email to you

**Comment by Yaswitha-MU** [comment]
Thank You

**Comment by Yaswitha-MU** [comment]
Sent the email, Bcc'd users. @vyshu1094: I'm seeing you as one of the user, can you confirm if you received the following email? 

Subject: Service Workbench (SWB) Maintenance  

  _Dear Service Workbench Users,
  We are upgraded the SWB system for better performance and few interface changes on December 27th. The system will be down all evening and any errors with the upgrades will be handled further. Due to holiday week any trouble shoots might take time, please be patient with us._
   
 _Thank You,_
 _NextGen BMI Center_

**Comment by vyshu1094** [comment]
Yes

**Comment by fergusonsha-umkc** [comment]
Note for today's planned activity:  Will be checking around 5PM for any Service Workbench use and doing point-in-time direct notifications on their workspaces if any are logged into, then preparatory remapping of workspace identifiers around 7PM before shutting down logins and any running workspaces to perform the framework upgrade, workspace template and configuration imports, and stopped workspace remaps in-system before a startup and login test of each.

**Comment by fergusonsha-umkc** [comment]
Inventoried 82 non-terminated workspaces, only 2 running presently.  Prep-work for kicking off the deployment script and importing the new workspace templates and configs is done.

**Comment by fergusonsha-umkc** [comment]
Workspaces and logins have been stopped, deployment is in progress.

**Comment by fergusonsha-umkc** [comment]
deployment completed fine, post-deployment site customizations were done, working on template, configuration, and account stack updates still...

**Comment by fergusonsha-umkc** [comment]
done with template imports and workspace configuration imports, working on account stack updates in order to test new workspace templates and configurations...

**Comment by fergusonsha-umkc** [comment]
well workspace type display order is not following the order of import, and nothing I do seems to be able to change the order it wants to be in... a battle for another hour...

**Comment by fergusonsha-umkc** [comment]
onboarded accounts are finally in 'Up-To-Date' status and pre-existing stopped workspaces are starting and connectable across those I've tested so far... just doing some finishing touches (hopefully) with new template launches before bed!

**Comment by fergusonsha-umkc** [comment]
I have one testing scenario to iron out once I get some rest, but 99% of all the testing on both pre-existing and newly-launched workspaces have passed, and all indicators within Service Workbench are green.  I re-opened login access and will close this out now :)
