### ISSUE TITLE
[Bug] SWB user name demonstration issue

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#37]
Current user name demonstration has duplicated last name: 

![image](https://user-images.githubusercontent.com/19035729/211861205-8545aa22-cd60-4674-821d-e4b84a70f7e3.png)

**Comment by fergusonsha-umkc** [comment]
This is due to users' full names being populated into the First Name field in their SWB user entries.  I'll get those cleaned up as part of this evening's Production update to v5.2.7 ... also already fixed in Dev :)

**Comment by sxinger** [comment]
not sure it is resolved on Dev account, as I'm still seeing my name display as: 

![image](https://user-images.githubusercontent.com/19035729/212400116-53849c7a-8d0b-48d4-be9e-664f659dcadf.png)

But I trust your discretion that this will be resolved eventually

**Comment by fergusonsha-umkc** [comment]
OK, I may have fixed it after you were already logged in and the UI info is still cached.  I'll double-check and test further in Dev.

**Comment by fergusonsha-umkc** [comment]
Ugh, appears to be getting overwritten at every login, I'll look deeper.

**Comment by sxinger** [comment]
> Ugh, appears to be getting overwritten at every login, I'll look deeper.

oh, it's fixed now. I guess there must be a bit delay in applying the changes. I think we are good.

**Comment by sxinger** [comment]
we then just need to fix it in production

**Comment by fergusonsha-umkc** [comment]
Well, hmm.  This stems all the way back to the SAML attribute mapping, which is now being auto-populated into the SWB user entries on each login.  name = Name means the SWB First Name field is getting mapped to the AWS SSO Display Name content.  I'm going to do some testing on how tricky this might or might not be to remap to name = GivenName, without breaking logins.

**Comment by fergusonsha-umkc** [comment]
OK this worked out, fixed this at the AWS SSO Application entry level to map attribute giveName instead of name (which is Display Name), and updated all existing user entries to reflect proper First Name and Last Name in all SWB environments.
