### ISSUE TITLE
[Bug] SAS workspace start with error

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#38]
I had trouble starting a SAS workspace after the upgrade: 

![image](https://user-images.githubusercontent.com/19035729/211865095-3621f4e3-d139-4e02-839a-5640081866a4.png)

**Comment by fergusonsha-umkc** [comment]
A known bug I'm working on getting debugged and fixed, didn't show up during testing, that occurs when only 1 "My Study" is linked to any type of workspace.  I had hoped to get it resolved by now but Fate intervened, it is a priority item I'm working on.  The workaround in the meantime to avoid the error (which is specifically "Policy statement must contain resources") is to select the "My Study" desired for use, as well as one of the Organization or Public studies, and then the IAM policy gets resources populated and the workspace will launch.  As soon as I figure out why it does this with just the 1 "My Study" linked, I'll update this issue.  I'm getting the minor-version upgrade from 5.2.2 to 5.2.7 tested and rolled out ASAP, which may fix the issue, but if not I have some idea where to start.

**Comment by sxinger** [comment]
What I did was selecting the previsioned Organization Study "GROUSE-MUIRB2057285-BC" (our recommended way to researchers), 
![image](https://user-images.githubusercontent.com/19035729/211869321-06411fa7-9243-44c6-87b5-e8b7f27f0822.png)

and deployed the SAS workspace under it. 

Are you suggesting that we should first create a My Study , selecting both the My Study and targeted Org Study, and then deploy SAS?

**Comment by fergusonsha-umkc** [comment]
It just needs to be more than 1 study selected as far as I've seen yet, one of which can be one of the public data sources (third tab). **However**, creating and selecting a My Study as well as their Org Study would also work, and might be a better idea to provide them a non-shared space for storing things, as a workspace launch procedure adjustment, which would also buy more time to get this issue resolved without blocking use... yeah, I recommend that. I'd only seen this occur with My Study selections, not Org Study selections (and I tested that, but not against the Research-GPC account yet), so this gives me another use case to debug.

Note that its _any_ workspace type, not just SAS, that this impacts...

**Comment by fergusonsha-umkc** [comment]
I have a few things to try before pushing the v5.2.7 upgrade in full, also, which I'll be testing asap today.

**Comment by sxinger** [comment]
Just tried the recommended approach, and still ended up with error: 

![image](https://user-images.githubusercontent.com/19035729/211871785-a45b35c2-9515-4832-9d5c-750c19ccab9d.png)

**Comment by fergusonsha-umkc** [comment]
Argh.  Well, the only difference I can see from what I had tested as working, is it being a Research-GPC project and study... :(  Can you test the workaround approach against a non-Research-GPC project and study, please?  Regardless, working on getting it fixed ASAP still, as I know it presents a major problem.

**Comment by sxinger** [comment]
May I have an estimate on when the issue will be resolved? We are in the process of onboarding a few new researchers onto the environment, which can be deferred. I would prefer to provide trainings when everything is back to normal.

**Comment by fergusonsha-umkc** [comment]
Can you give me 1 week please?

**Comment by fergusonsha-umkc** [comment]
By next Wednesday or sooner, I mean...

**Comment by sxinger** [comment]
That should work.

**Comment by sxinger** [comment]
Actually, as I think about it, connecting a MyStudy with a Org Study makes sense to me, operation-wise. In that way, the researcher will be able to have both a personal storage space and a shared storage space. I will just need to modify my training instruction accordingly.

**Comment by sxinger** [comment]
So, I think what we need to fix now, is to make is work with "Research-GPC" account. Do you need to re-establish the connection with that external account?

**Comment by sxinger** [comment]
I will report my testing with "UMBMI-Application-Prod-Project" in a little bit.

**Comment by fergusonsha-umkc** [comment]
Updating the account onboard stacks again is one of the things I'll be trying today, very carefully, yeah :)

**Comment by sxinger** [comment]
> I will report my testing with "UMBMI-Application-Prod-Project" in a little bit.

Still errored out...

**Comment by sxinger** [comment]
(weird... I can't attach figures...)

The following is the error message: 

Error provisioning environment Song-test-upgrade-windows-workspace. Reason: Errors from CloudFormation: [{LogicalResourceId : SC-564303459249-pp-ovfbbwj2h4fqe, ResourceType : AWS::CloudFormation::Stack, StatusReason : The following resource(s) failed to create: [IAMRole]. Rollback requested by user.}, {LogicalResourceId : IAMRole, ResourceType : AWS::IAM::Role, StatusReason : Policy statement must contain resources. (Service: AmazonIdentityManagement; Status Code: 400; Error Code: MalformedPolicyDocument; Request ID: be5238ca-d25f-43bb-8baf-a581b7e3a744; Proxy: null)}, {LogicalResourceId : IAMRole, ResourceType : AWS::IAM::Role, StatusReason : Resource creation Initiated}, {LogicalResourceId : SecurityGroup, ResourceType : AWS::EC2::SecurityGroup, StatusReason : Resource creation Initiated}, {LogicalResourceId : InstanceRolePermissionBoundary, ResourceType : AWS::IAM::ManagedPolicy, StatusReason : Resource creation Initiated}, {LogicalResourceId : SC-564303459249-pp-ovfbbwj2h4fqe, ResourceType : AWS::CloudFormation::Stack, StatusReason : User Initiated}]

**Comment by fergusonsha-umkc** [comment]
Darn it, OK, I've cleared my afternoon/evening as much as possible in order to focus on this.

**Comment by fergusonsha-umkc** [comment]
It may have worked for me due to the admin role and having my user linked to all existing projects.

**Comment by fergusonsha-umkc** [comment]
The issue does not seem to be manifesting under the from-fresh Sandbox SWB environment, so I can use that as a comparison (it's relatively customization-free also) to find and fix the potentially missing or incorrect piece of the puzzle.  The account onboard stacks are up-to-date, verifying both in CloudFormation against the onboard.cfn.yml shipped with the v5.2.2 source, and in SWB's Accounts section, so the problem may be in the workspace templates or parameters; I'm  reviewing and comparing stack parameters being passed in between these 2 working and not-working SWB environments for the same workspace type also.  The error seems to indicate that a policy that is supposed to be passed in, is empty, but the parameters for the workspace stacks that failed don't show an empty IamPolicyDocument (what I first suspected) and that parameter is as-expected for the selected study/studies.  However, even though the new Egress Store feature they introduced is disabled (since we haven't had time to test that or train people on its use if we wanted to implement it), I do see an empty EgressStoreIamPolicyDocument parameter being passed in still, which may be the empty policy statement that's tripping the whole stack up... starting there on fixing this...

**Comment by sxinger** [comment]
@fergusonsha-umkc please feel free to reach out to SWB support team (Nathan and Travis) if needed.

**Comment by fergusonsha-umkc** [comment]
OK, figured out why the org study I tested under the Dev environment, passed, alone and in combination... it is from an external data source, not an org study under the host account.  Seems this is impacting studies living under the host account, only.  This helps me narrow things down and explains some mysteries... I also identified the empty Resource value in the iamPolicyDocument parameter (the parameter itself is not empty, but that value is, for a permission set its trying to add), now I can trace back through the templates, where iamPolicyDocument gets built, to determine why.

**Comment by fergusonsha-umkc** [comment]
Going to do the minor-version upgrade to latest 5.2.7 release, minimally disruptive, in the hopes of introducing positive change and to make sure we're on their latest release before reporting a bug.  I did this in Sandbox already yesterday so it will also ensure fewer differences, for comparison.

**Comment by fergusonsha-umkc** [comment]
OK, good news, getting positive test results after the version upgrade to 5.2.7 and reimporting the workspaces and recreating the configurations manually, so far.  Doing thorough testing of each type of workspace and study combination before calling it good and doing the same process under Production.  Bonus: figured out where to configure our various UI customizations within the source tree via additional settings YAML files.  I've updated the minor-version upgrade wiki page to reflect these pre-configuration steps.

**Comment by sxinger** [comment]
Can you include the wiki page url here?

**Comment by fergusonsha-umkc** [comment]
https://github.com/Missouri-BMI/NextGen_Cloud_Architecture_AWS/wiki/AWS-SWB-Minor-Release-Upgrade-Procedure

I've already added it and the major-version upgrade process I performed, going from v3 to v5, in the wiki's nav sidebar under Change Management also :)

**Comment by fergusonsha-umkc** [comment]
Update: Sagemaker and Linux workspaces and configurations are rebuilt and pass iterative testing across single and multiple combinations of study selections, in the Dev SWB 5.2.7 environment.  Working on rebuilding and testing Windows, SAS, and CLAMP workspaces and configurations....

**Comment by fergusonsha-umkc** [comment]
Update: Windows/SAS/CLAMP workspace configurations are recreated and tested as launching against studies ok, however I am now debugging an issue in our v5.2 Windows template: under v5.2.7 the powershell preinstall scripts created in the template are not running properly.  Initial suspicion is that they changed or removed a variable that was being used in the Powershell commands to specify the environment-bootstrap-scripts bucket.  Always some new wrinkle... but on track still!

**Comment by fergusonsha-umkc** [comment]
HAH!  Problem was not in the templates, whew.  The 5.2.7 upgrade reset the contents of the bootstrap-scripts bucket, which would be why none of our custom files could be found when running the installerDonwload.ps1 constructed script 🤦‍♂️ So I should just need to restore our custom scripts and installer files from the Prod or Sandbox bucket to fix it... short-term, along with adding instructions to the upgrade wiki doc to compensate for this possibility.  Long-term, will probably move our custom files into our own custom bucket instead of using their bucket, so it doesn't get clobbered during an upgrade again.

**Comment by fergusonsha-umkc** [comment]
Wiki doc updated and installer files/scripts restored, testing all Windows workspaces again.

**Comment by fergusonsha-umkc** [comment]
Windows workspace testing is showing positive results, for both single and multiple study connections; going to do further testing for all workspace types under the researcher role now, this morning, and then begin prepping to upgrade Production in kind aiming for minimal disruption.

**Comment by fergusonsha-umkc** [comment]
@sxinger if you have time today could you also do some testing in Dev SWB to give additional validation?  Appreciate it :)

**Comment by fergusonsha-umkc** [comment]
I've been hesitant to add Research-GPC to the Dev SWB environment in case it should conflict with the Prod SWB stack resources, but I'll look into that.

**Comment by fergusonsha-umkc** [comment]
All my tests have passed under Dev, so I am preparing everything to get Production updated and tested after-hours today.

**Comment by sxinger** [comment]
> @sxinger if you have time today could you also do some testing in Dev SWB to give additional validation? Appreciate it :)

I tried out several use cases which I think is more relevant, my acceptance test reports are as follows:
1. Single Org Study with SAS workspace - pass
2. Org Study + Public with Sagemaker - pass
3. Org Study + MyStudy with standardized windows - pass
4. Org Study + MyStudy with standardized linux - pass

**Comment by fergusonsha-umkc** [comment]
Excellent, thanks very much!

**Comment by fergusonsha-umkc** [comment]
Doing Production upgrade now...

**Comment by fergusonsha-umkc** [comment]
Production upgrade complete, workspace configurations updated, testing and re-enabling workspaces as they succeed

**Comment by fergusonsha-umkc** [comment]
All workspace types passed launch testing against various study selections, in Production.  Please also test things out before we close this issue as resolved.  Thanks!

(P.S. Making another attempt to influence the display order of workspace types for better flow, is still on my radar also.)
