### ISSUE TITLE
[Feature Request] Increase storage in SAS SWB workspace - Rana

### ISSUE THREAD

**Issue by kzraryan-mu** [Missouri-BMI/service-workbench-on-aws#40]
I need to have the following in the newly deployed  SAS SWB-
- Increase E: (Export) drive storage to 2TB
- Increase T: drive(SAS Temp) storage to 1TB
- Refer to https://github.com/Missouri-BMI/P_2_SASDB_EDC/issues/58 for background.

SAS-SWB Details:
- Name : PCORnetQuery-SAS-MRKFW
- ID:  7c94825e-8248-41af-bbc0-8e38f4ced4b2

The other SWB had this note in detail. I hope this helps you.
"NOTE: Post-deployment customized, termination protection enabled on CFN Stack."

**Comment by fergusonsha-umkc** [comment]
Disks have been grown, and tagged with the 'Outback-Engineering' project identifier :)

Please note the recurring monthly cost of these (whether the workspace is in use or not) is now $26.33 for the 1TB gp3 SAS_TEMP disk, and $14.28 for the 2TB st1 SAS_EXPORT disk.

**Comment by kzraryan-mu** [comment]
@vasanthi014 @fergusonsha-umkc 
I have looked into the differences between gp3 and st1. Pricewise and task-wise, shouldn't we use st1?

As the workspace/storage will be used by one user and mostly one program, we are not utilizing the benefit of gp3 (low frequency). And also, the SAS programs we are running are mostly large sequential read/write operations which is st1's feature.


Give it a read, and you can decide.

Ref: https://aws.amazon.com/about-aws/whats-new/2021/06/amazon-ebs-now-supports-gp3-st1-and-sc1-volume-types-in-the-los-angeles-aws-local-zones/

**Comment by fergusonsha-umkc** [comment]
We can definitely convert SAS_TEMP to st1 if you want to see what the performance is like on that, and switch to that for all existing and future SAS workspaces... we had decided to keep it at gp2/3 for performance reasons as its the disk that will have the highest I/O during SAS operations when it needs to use disk caching.

**Comment by kzraryan-mu** [comment]
Sorry, I didn't see that for SAS_EXPORT we are already using st1. The current implementation looks fine to me. In the future, we can avoid using the SAS Export (the 2TB). I will be working towards that.

**Comment by fergusonsha-umkc** [comment]
No worries, and awesome :)

**Comment by fergusonsha-umkc** [comment]
We will likely be moving from gp2 to gp3 across the board for fast disks, though, as it comes out to be a lesser expense even when provisioned at 200MBps (slightly higher than the 188MBps comparable to gp2 performance).

**Comment by kzraryan-mu** [comment]
@fergusonsha-umkc, the SWB's threshold to auto shutdown needs to get lower. Should I create a different ticket?

**Comment by fergusonsha-umkc** [comment]
No, I will adjust it for your workspace.

**Comment by fergusonsha-umkc** [comment]
Adjusted.

**Comment by kzraryan-mu** [comment]
Thank you.
