### ISSUE TITLE
[Question] Upgrading to a larger instance of Sagemaker?

### ISSUE THREAD

**Issue by ghkkhan** [Missouri-BMI/service-workbench-on-aws#43]
@fergusonsha-umkc - I was referred to you about an issue. I initially created a small workspace (2 cpu 4gb ram) to replicate the results of someone else's code.

In addition to that, I used that instance to do some basic prototyping of a different program. The program runs fine, but now I need a bigger instance so that the program doesn't crash on larger data files. I tried to create a bigger instance, but it failed. 

How should I go about this. Can you create a new instance for me, or upgrade the pre-existing one? one with 4 cores and at least 8GB would be good for now, I think.

**Comment by fergusonsha-umkc** [comment]
No problem, I can swap in a different instance type on your current workspace.  What is the workspace name/id?  Do you need any additional disk space, or just CPU and RAM?

**Comment by fergusonsha-umkc** [comment]
Also, came across this important note regarding changing Sagemaker instance types...
"If you change the instance type, unsaved information and existing settings for the notebook are lost, and installed packages must be re-installed."

So I'd recommend saving off anything you haven't already, or into an attached study folder is fine, and make note of the packages you have installed.

**Comment by fergusonsha-umkc** [comment]
Please also stop the workspace when you are ready for it to be resized :)

**Comment by ghkkhan** [comment]
The work space is stopped.
Everything is saved to GitHub so no problems there.

The ID is  642ed77f-ba0b-4bb7-860d-703bfe07f5ee. The name is: ObesityStudyWorkspace.

I don't think the disk size should be an issue, but can you tell me what it is right now? If its not less than 15GB then it should be OK.

**Comment by fergusonsha-umkc** [comment]
It was 5GB for the core disk, I've set it to 15GB and instance type ml.t3.xlarge for 4 vCPU and 16GB RAM. I tested startup and connectivity, have stopped it again.  Let me know when its OK to close this request out or if we need to adjust again :)

**Comment by ghkkhan** [comment]
@fergusonsha-umkc - Thanks a lot. Everything is working without a hitch now.
I'll close this request now.
