### ISSUE TITLE
Error in SWB workspaces page

### ISSUE THREAD

**Issue by vasanthi014** [Missouri-BMI/service-workbench-on-aws#44]
![image](https://github.com/Missouri-BMI/service-workbench-on-aws/assets/14314511/fe95fabf-aac1-426f-a3f0-cea04c025ebf)

**Comment by fergusonsha-umkc** [comment]
Looking into this asap

**Comment by fergusonsha-umkc** [comment]
Every time we update to a new template for workspaces, we now have to remap all the pre-existing workspaces to the new template's identifier, sigh.  Apologies for forgetting to do that.  Running the requisite batch process against DynamoDB now.

**Comment by fergusonsha-umkc** [comment]
Should all be fixed now, please let me know if otherwise, or close this ticket if so :)
