### ISSUE TITLE
[Misc] Showing high cost for unused SWB

### ISSUE THREAD

**Issue by kzraryan-mu** [Missouri-BMI/service-workbench-on-aws#45]
Hi, My SWB which I haven't used for a while is showing more than 23$ cost just for yesterday.

![image](https://github.com/Missouri-BMI/service-workbench-on-aws/assets/73001275/ad66a835-2562-424d-a115-9f346c54c252)

**Comment by kzraryan-mu** [comment]
Even both the workspaces were unused this week, but suddenly there is a cost hike.

![Screen Shot 2023-06-16 at 1 27 41 AM](https://github.com/Missouri-BMI/service-workbench-on-aws/assets/73001275/c4700aa7-7640-4b94-b711-9fa37b55637d)
![Screen Shot 2023-06-16 at 1 27 26 AM](https://github.com/Missouri-BMI/service-workbench-on-aws/assets/73001275/9d44ac6f-c6c3-4945-b958-c76d7a5e069b)

**Comment by fergusonsha-umkc** [comment]
This is reflective of this week being patch week where we spin up all the workspaces long enough to get the OS/Microsoft patching done as well as the 3rd-party software updates done.  We do this the week of the 2nd Tuesday every month.
