### ISSUE TITLE
[Feature Request] Install git on standardized windows workspaces

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#7]
Install git on standardized windows workspaces from http://git-scm.com/downloads

**Comment by aaronmbruce** [comment]
Git is ready to be added in prod, and is currently available in app-dev

**Comment by vasanthi014** [comment]
@sxinger Will test if git is installed in standard workspaces in app-dev

**Comment by sxinger** [comment]
I validated the git installation on windows workspace, which is working fine. Please move it into production @aaronmbruce

**Comment by aaronmbruce** [comment]
This is now in prod
