### ISSUE TITLE
[Feature Request] s3-synchronizer doesn't sync with S3 bucket

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#8]
**Describe the bug**
Under organization study, I tried to save some data files (< 2MB) under the shared D:/ drive: 
![image](https://user-images.githubusercontent.com/19035729/140417836-6fac5975-7cd3-4dac-924b-49934a7e68a4.png)

It saved on the EC2 disk, however, it did not sync with the underlying S3 bucket (I left the workspace on for at least 10 minutes for it to sync: 
![image](https://user-images.githubusercontent.com/19035729/140419352-c59d6ca6-5ed5-44fe-b5f0-0b797d243cb1.png)

The following is what recorded in the s3-synchronizer-stdout.txt
![image](https://user-images.githubusercontent.com/19035729/140418150-b0b4545b-5759-4baa-b093-e5d4fc2face0.png)

**Expected behavior**
We would expect the data can be synchronized with S3 bucket relatively in real-time, so that researchers can have a permanent storage location and share data (under organization study).

**Comment by fergusonsha-umkc** [comment]
This is likely related to #9

**Comment by fergusonsha-umkc** [comment]
Fielding bug report discussion with Travis, thank you for initiating that @sxinger

**Comment by fergusonsha-umkc** [comment]
As we determined this was due to mis-matched permissions, can we close this out?

**Comment by fergusonsha-umkc** [comment]
This was due to study permissions and cross-project study/user alignment, sorted out and working now.
