### ISSUE TITLE
(Rclone Mount) [Bug] AWS workspace FS roleArn could break

### ISSUE THREAD

**Issue by sxinger** [Missouri-BMI/service-workbench-on-aws#9]
**Describe the bug**
Under organization study, a new user who launches a new workspace may overwrite a fs roleArn, leading to the lose of data access among the existing users/workspaces. We have communicated this error with AWS SWB Dev team: https://umkc.box.com/s/12ty3uc8uvkn1uybw4ra7452jlbnfhom

**Comment by fergusonsha-umkc** [comment]
Primary approach I will take to remediate this issue is to build in a dynamic query for the correct role to use, within the rclone mount and s3 sync startup scripts, using the aws cli and available EC2 metadata.  If that isn't feasible, I will store the role ARN in a state file, at the top level of the study buckets, which will be updated and referenced via the startup scripts.

**Comment by fergusonsha-umkc** [comment]
Looking into using https://awscli.amazonaws.com/v2/documentation/api/latest/reference/iam/get-user-policy.html to pull the roleArn from the primary IAM policy attached to the workstation

**Comment by fergusonsha-umkc** [comment]
also possible to fetch the EC2 instance metadata via it's internal http resource and see if the role gets stored anywhere in there

**Comment by fergusonsha-umkc** [comment]
Looks like using aws iam list/get-attached-role-policies is possible, at startup, but I need to update the permissions boundary policy that gets generated and linked during the workspace stack deployment, to permit the instance role to query its own attached role policies... maintaining a state file may be a faster fix for now, until I can figure all that out

**Comment by fergusonsha-umkc** [comment]
Ahhhh but a state-file won't work, because once the roleArn changes, older workspaces won't be able to read it anyways, shoot.  OK, I _have_ to be able to dynamically query the *-s3-study-bucket attached role policy to pull the correct roleArn for external studies...

**Comment by fergusonsha-umkc** [comment]
OK, figured out the role permissions and boundary changes needed, now to figure out where they get set

**Comment by fergusonsha-umkc** [comment]
PS script commands to obtain roleArn from s3-study-bucket role policy:

`$roleIdentity = aws sts get-caller-identity | ConvertFrom-JSON`
`$rolePolicies = aws iam list-role-policies --role-name $roleIdentity.Arn.Split('/')[1] | ConvertFrom-JSON`
`$s3StudyBucketPolicy = aws iam get-role-policy --role-name $roleIdentity.Arn.Split('/')[1] --policy-name $rolePolicies.PolicyNames[1] | ConvertFrom-JSON`
`$roleArn = $s3StudyBucketPolicy.PolicyDocument.Statement | Where Sid -eq "studyAssumeRoles" | Select Resource`
`$roleArn.Resource`

**Comment by fergusonsha-umkc** [comment]
... where only one external study is connected, but, what does it look like for multiple...

**Comment by fergusonsha-umkc** [comment]
Good thing is, looks like I can add the requisite role permissions/boundaries in the Service Catalog template, where its getting dynamically generated:
IAMReadOnlyAccess as an attached permissions policy
then
"Effect": "Allow",
            "Action": [
                "iam:ListRolePolicies",
                "iam:GetRolePolicy"
            ],
            "Resource": "arn:aws:iam::124941922627:role/analysis-##########-ec2-role"

**Comment by fergusonsha-umkc** [comment]
Testing and debugging new rclone mount workspace template, and associated Powershell scripts, to set up read-only IAM access needed for said scripts to dynamically pull the roleArn to be used for an external study, plus all the automatic rclone bucket mounting logic.

**Comment by fergusonsha-umkc** [comment]
Template with policy customization to allow IAMReadOnly access to the role attached polcies for the ec2-role has been imported (App-Dev) as a new Windows workspace version, and tested, working.

**Comment by fergusonsha-umkc** [comment]
Doing final testing/debug of install-rclone.ps1 and start-rclone-mount.ps1 with new roleArn dynamic query piece

**Comment by fergusonsha-umkc** [comment]
Oops, need to add an s3 bucket copy directive to the template to get the scheduled task xml file, and import it.  Also, add logic to kick off a run of the task after install-rclone.ps1 completes.  All the other pieces are working!

**Comment by sxinger** [comment]
@fergusonsha-umkc  Let me know when you need me to test it out.

**Comment by fergusonsha-umkc** [comment]
Barring unexpected distractions, I have another full focus day, aiming to have this testable by EOB.

**Comment by fergusonsha-umkc** [comment]
OK, I believe at this point I can say the workspace type "EC2-Windows-v5dot3-with-rclone-full-auto" under the App-Dev SWB instance is ready for testing (by someone other than me)!  <fingers crossed> @sxinger

**Comment by fergusonsha-umkc** [comment]
I might need to massage the start script to provide some progress indication, because they don't show up mounted right away, upon login... YMMV since its part of the whole login prep sequence.

**Comment by fergusonsha-umkc** [comment]
Well, maybe not... it takes a bit on a fresh workspace launch, but afterwards on stops and starts it's pretty immediate.

**Comment by sxinger** [comment]
@fergusonsha-umkc should I test it out under the Application-Dev account?

**Comment by fergusonsha-umkc** [comment]
@sxinger yes, ready for testing under Application-Dev Service Workbench.  You have researcher role under there, for testing within that experience

**Comment by fergusonsha-umkc** [comment]
Fixed a missing variable check in start-rclone-mount.ps1 script, please recreate any testing workspaces

**Comment by sxinger** [comment]
**Test 1 - MyStudy-Single**

D: drive showed up at first launch, with a folder name same as the backend s3-bucket name (same as the study name): 
![image](https://user-images.githubusercontent.com/19035729/145450473-950f0589-7a22-4ffe-9adf-c2d2ee739812.png)

Save a test file in D: drive which appears in S3 bucket and stop-restart the instance doesn't remove the file:
![image](https://user-images.githubusercontent.com/19035729/145454365-bd226a40-038d-4314-ae49-6028446cb978.png)

**Comment by sxinger** [comment]
**Test 2 - MyStudy-Multiple**

D: drive dosen't appear on initial launching. After stop-restart, it does appear as two separate network drive (D: , E:): 
![image](https://user-images.githubusercontent.com/19035729/145458947-bec71686-15d4-42a0-ae5e-0061c12cf3c4.png)
- need to include this in SWB User Guide @sxinger 

The file saved in D: file showed again (after workspace termination), and save a test file in E: drive which also appears in S3 bucket. Stop-restart the instance doesn't remove the file

**Comment by fergusonsha-umkc** [comment]
It does take significantly longer for the drives to appear on initial launch, because of the first-time user login profile setup also going on, but they do eventually get mounted once the process gets to that task.  Around 45s-1m last check.

**Comment by fergusonsha-umkc** [comment]
Thanks for this testing thoroughness :)

**Comment by sxinger** [comment]
**Test 3 - OrgStudy-Multiple**
In this test, I assume different roles between two Org Studies: test-rclone3 (admin); test-rclone4 (admin, readwrite). It also takes a re-start to enable the access to both network drivers. And it shows expected behavior: 
-- not allow creating file in test_rclone3
![image](https://user-images.githubusercontent.com/19035729/145472086-6f9bfbd3-cb3d-4f8d-a54f-0c58452a92bd.png)

-- allow creating file in test_rclone4
![image](https://user-images.githubusercontent.com/19035729/145472460-2763d380-e996-4373-a80c-3b2408799215.png)

Although I haven't done stress test on whether large-sized data would change the behavior, I'm happy with the current status and would like to move this to production. Great job, Shaun!

**Comment by fergusonsha-umkc** [comment]
Thanks! :). I'll aim to get this into production in the core Windows template within the next week!

**Comment by fergusonsha-umkc** [comment]
I think Rana and Vasanthi have pretty well stress-tested the large file performance in their manually-converted workspaces.  So we know, if data files pulled from a data source are temped or cached through the C: drive, it should still be upsized to accommodate the largest of those (e.g. when using SAS as the tool).  Otherwise he was able to get into the 40+GB range without issues, writing to the rclone virtual disk.

**Comment by fergusonsha-umkc** [comment]
... but that would be the case regardless of rclone, really. He'd have hit that issue with s3-synchronizer also, because it was C: that was running out of space, on the 175GB table.

**Comment by fergusonsha-umkc** [comment]
... and we can spot-add temporary EBS storage to any workspace on-demand, to suit a variety of scenarios requiring local actualized storage needs.

**Comment by fergusonsha-umkc** [comment]
Apologies but with the log4j vulnerability mitigation work and other random issues that absorbed my attention this week, I have not gotten this template modification moved into production yet.  We are also doing some performance testing and tuning of the SAS workspaces regarding their write cache, which I may want to put into the default deployment scripts.

**Comment by fergusonsha-umkc** [comment]
Waiting to see if changes to default configuration for the write cache has resolved stress-break issues with SAS workspace high-volume utilization, before calling this ready for production yet.

**Comment by fergusonsha-umkc** [comment]
As an additional option, based on the stress-testing and issues with token timeout and large data file writes with the rclone mounted D: drive in Rana's SAS workspace, I'm going to be exploring the use of the (paid) similar-functionality app called Expandrive, and stress-testing it to see if it might provide a more polished experience.  This may be a case-by-case solution to pivot to for some instances.

**Comment by fergusonsha-umkc** [comment]
These specialized workspaces may also just need to be configured with a >250GB C: drive to accommodate a >200GB write cache, but the token timeout issue for the cross-account role needed to access the study buckets from external accounts (e.g. Staging-Data) is still a significant problem where long-run jobs are concerned... may not be able to get around having to use s3-synchronizer in these cases.

**Comment by fergusonsha-umkc** [comment]
Considering adding the rclone mount version of Windows workspaces as an additional option alongside the s3-synchronizer option, a la "Network-Attached Study Data" and "Disk-Synced Study Data" with cost estimates accordingly, and they can be switched between as best suits the study data access requirements of a researcher's projects...

**Comment by fergusonsha-umkc** [comment]
@abruce added you for visibility and awareness, and to bring you into the implementation discussion herein

**Comment by fergusonsha-umkc** [comment]
Remember: there are no magic bullets! :)

**Comment by fergusonsha-umkc** [comment]
Please review and approve these top-level workspace panes, thanks!
![image](https://user-images.githubusercontent.com/81329060/148807463-30d0a244-b072-4201-ac52-a38569689587.png)
![image](https://user-images.githubusercontent.com/81329060/148807571-f993af36-b963-4e1d-84b4-3c518d04b917.png)

**Comment by fergusonsha-umkc** [comment]
After massage and approval of these, I'll move into production

**Comment by fergusonsha-umkc** [comment]
This has been moved into production, and workspace descriptions updated to reflect study access methods (Network-Connected, Fully Synced).  Please open new tickets for post-production bugs or changes to workspaces using Network-Connected Studies.
